### ISSUE TITLE
About the "ResNet" backbones weights

### ISSUE THREAD

**Issue by liminn** [AntiAegis/Semantic-Segmentation-PyTorch#11]
Thanks for you work!
 I have two questions:
- Where to get the "ResNet" backbones pretrained weights? 
- ```Python
   def resnet50(pretrained=None, **kwargs):
	model = ResNet(Bottleneck, [3, 4, 6, 3], **kwargs)
	if pretrained is not None:
		model._load_pretrained_model(pretrained)
	return model
   ```
   where is the definition of function `_load_pretrained_model`?

**Comment by brianFruit** [comment]
Hi @liminn, did you find out how to get the backbones?
