### ISSUE TITLE
ModuleNotFoundError: No module named 'timm.models.gen_efficientnet'

### ISSUE THREAD

**Issue by ivan-v-kush** [AntiAegis/Semantic-Segmentation-PyTorch#17]
get such error,
installed timm using `pip3 install timm`

run `python3 inference_webcam.py  --checkpoint UNet_MobileNetV2.pth `

**Comment by bigpo** [comment]
> get such error,
> installed timm using `pip3 install timm`
> 
> run `python3 inference_webcam.py --checkpoint UNet_MobileNetV2.pth `

may i ask you how to solve this problem ?

**Comment by ivan-v-kush** [comment]
sorry, but i've forgot already =(

**Comment by bigpo** [comment]
I degrade the version of timm solved this issue.

**Comment by SergeiSamuilov** [comment]
What version of timm is required?

**Comment by aatishrana495** [comment]
pip3 install timm==0.1.10 worked for me on ubuntu 18.04

**Comment by melaanya** [comment]
It is also enough to do
```
git submodule sync
git submodule update --init --recursive
pip install -e models/pytorch-image-models
```

as the required version of  `timm` is incorporated in this repo.
