### ISSUE TITLE
submodule clone error

### ISSUE THREAD

**Issue by bcsefercik** [AntiAegis/Semantic-Segmentation-PyTorch#22]
https://github.com/AntiAegis/pytorch-image-models is private repo. I cannot clone the repo. Therefore, I am not able to run the scripts.

**Comment by rafellerc** [comment]
I'm not sure if the account is private, deleted or if that was the author's previous account name but I managed to make it work by getting it from other sources.

Try: `git clone https://github.com/thuyngch/Human-Segmentation-PyTorch.git`
and replace  
`url = https://github.com/AntiAegis/pytorch-image-models` 
with
` url = https://github.com/rwightman/pytorch-image-models`
in `.gitmodules`

Before executing `git submodule update --init --recursive`

**Comment by bcsefercik** [comment]
Thank you. It worked.

**Comment by san-guy** [comment]
Hey it is seems you guys solved the issue recently. I tried inferencing on some images but the results were very poor.
It seems like someone replaced the pre-trained model with a one at epoch-1 or less.

Results are really bad even with all backbone plus on any video.

Can you guys share me previous pre-trained models?
